package com.minecraftabnormals.biome_vote_losers.client.animation.definitions;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;

@OnlyIn(Dist.CLIENT)
public class MeerkatAnimation {
	public static final AnimationDefinition STAND_UP = AnimationDefinition.Builder.withLength(0.24f).addAnimation("head", new AnimationChannel(AnimationChannel.Targets.POSITION, new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR), new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 9f, 8f), AnimationChannel.Interpolations.LINEAR))).addAnimation("body", new AnimationChannel(AnimationChannel.Targets.POSITION, new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR), new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 13f, 0f), AnimationChannel.Interpolations.LINEAR))).addAnimation("body", new AnimationChannel(AnimationChannel.Targets.ROTATION, new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR), new Keyframe(0.24f, KeyframeAnimations.degreeVec(-90f, 0f, 0f), AnimationChannel.Interpolations.LINEAR))).addAnimation("leftArm", new AnimationChannel(AnimationChannel.Targets.POSITION, new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR), new Keyframe(0.24f, KeyframeAnimations.posVec(1f, 7f, 6f), AnimationChannel.Interpolations.LINEAR))).addAnimation("leftArm", new AnimationChannel(AnimationChannel.Targets.ROTATION, new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR), new Keyframe(0.24f, KeyframeAnimations.degreeVec(-25f, 0f, 0f), AnimationChannel.Interpolations.LINEAR))).addAnimation("rightArm", new AnimationChannel(AnimationChannel.Targets.POSITION, new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR), new Keyframe(0.24f, KeyframeAnimations.posVec(-1f, 7f, 6f), AnimationChannel.Interpolations.LINEAR))).addAnimation("rightArm", new AnimationChannel(AnimationChannel.Targets.ROTATION, new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR), new Keyframe(0.24f, KeyframeAnimations.degreeVec(-25f, 0f, 0f), AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition STOP_STAND = AnimationDefinition.Builder.withLength(0.24f).addAnimation("head", new AnimationChannel(AnimationChannel.Targets.POSITION, new Keyframe(0f, KeyframeAnimations.posVec(0f, 9f, 8f), AnimationChannel.Interpolations.LINEAR), new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR))).addAnimation("body", new AnimationChannel(AnimationChannel.Targets.POSITION, new Keyframe(0f, KeyframeAnimations.posVec(0f, 13f, 0f), AnimationChannel.Interpolations.LINEAR), new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR))).addAnimation("body", new AnimationChannel(AnimationChannel.Targets.ROTATION, new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 0f, 0f), AnimationChannel.Interpolations.LINEAR), new Keyframe(0.24f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR))).addAnimation("leftArm", new AnimationChannel(AnimationChannel.Targets.POSITION, new Keyframe(0f, KeyframeAnimations.posVec(1f, 7f, 6f), AnimationChannel.Interpolations.LINEAR), new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR))).addAnimation("leftArm", new AnimationChannel(AnimationChannel.Targets.ROTATION, new Keyframe(0f, KeyframeAnimations.degreeVec(-25f, 0f, 0f), AnimationChannel.Interpolations.LINEAR), new Keyframe(0.24f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR))).addAnimation("rightArm", new AnimationChannel(AnimationChannel.Targets.POSITION, new Keyframe(0f, KeyframeAnimations.posVec(-1f, 7f, 6f), AnimationChannel.Interpolations.LINEAR), new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR))).addAnimation("rightArm", new AnimationChannel(AnimationChannel.Targets.ROTATION, new Keyframe(0f, KeyframeAnimations.degreeVec(-25f, 0f, 0f), AnimationChannel.Interpolations.LINEAR), new Keyframe(0.24f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR))).build();


	public static final AnimationDefinition DIG = AnimationDefinition.Builder.withLength(3.16f)
			.addAnimation("normal",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.04f, KeyframeAnimations.posVec(0f, -15f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("normal",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.04f, KeyframeAnimations.degreeVec(54.47580563953079f, 7.06014616141556f, 8.691429503279323f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.56f, KeyframeAnimations.degreeVec(27.5f, 10f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.04f, KeyframeAnimations.degreeVec(27.5f, -10f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.56f, KeyframeAnimations.degreeVec(27.5f, 10f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.04f, KeyframeAnimations.degreeVec(27.5f, -10f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.6f, KeyframeAnimations.degreeVec(27.5f, 10f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.08f, KeyframeAnimations.degreeVec(27.5f, -10f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leftArm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.04f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.56f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.08f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.6f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.12f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("rightArm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.04f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.56f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.08f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.6f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.12f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leftLeg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.04f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.56f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.08f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.6f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.12f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("rightLeg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.04f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.56f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.08f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.6f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.12f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition DIGUP = AnimationDefinition.Builder.withLength(0.8f)
			.addAnimation("normal",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, -8f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.56f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("normal",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-87.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leftArm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("rightArm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leftLeg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("rightLeg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR))).build();
}
